sudo: required
language: minimal
services:
- docker
install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="grafana"
script:
- export DOCKER_TARGET="${ECR_REPO}/${ARTIFACT_NAME}:ci-${TRAVIS_BUILD_NUMBER}"
- docker build -t ${DOCKER_TARGET} .
deploy:
  provider: script
  script: "./ci-tools/build/upload-image.sh $ARTIFACT_NAME"
  on:
    all_branches: true
env:
  global:
  - secure: vXP7TF5f8oeG9u7nBS88egc5ju7TI0k/VLq75IhxcJyFmBjjQeNXXmhCQIWgdQnFsCmHpw0Kp4RqWJ8GAmSU26/hNqf3KWLrm0QSX4m8eDEYoQDH4vXw1ldq+4+zsifpZoi+uBNw3i7ohmXoGB3BNskqtjwSScFobZKrr40fF2KtVmexCVUKsQiWknBKe1x17+gLZ+A2CgleepEeqOP6P82pwnDCHT4cgkGUKBsqXu/jlVAgR1i4cTJmtFuGZt5bUZ6DnBI3UuC9YS2MR+R0w9MF/XDOZdzV7n/49QOxoj7zA12pDw4KbX2avd2tDQLg765YBdymHpZW8/FymUgkbqeP+XSTmV2CeS2ngvP2ciZMX/dq6tiQ4uII2xZAnV03jec3o0Em6mUixyrgOe/8pfX3ecjEHp87QsFH17vheU68kfSYJnHrQ49ZC2nNOv7hgdon0tzj0JFfuxFvIbGvL7iNrwCj8Zm9x35TdOj1xYue04YrlB67VRcuZQqdwbTftOx2Jf2cJZWe8rh/DoM/Oixy2zysgW8+yxp25nvO/QqEysuMIQwgeUAturdmTNFea6EmEJNRKzNZw84qwEFAI7V97ZqIm388L/YdqoO5Agudf2KCk9zyzY9VVIhQWlw4WRsXR48ktmiKm8oFXNtkA/8Zv7QT/ZgtxFRY0ZEY3pQ=
  - secure: vsRCL/Bf7dHIcdKWtjN6eDmAowmEHq4uMOLlI2bDu4A/PV+vkHLQDRTzldAOuCnMXr6Sp9Q0gwWlyccuF2qERlRdI87Wipv+lZwCMmXVU8W7FCs/qWJfSxsWA1BwGatDBeRamRqoieg/lgUksj+zimLX0A3yS9/CJwq4SJHuP69OyiO7t9xXZdgoGo1F0gkrQLvoBsW7FehyWeWBs6kLbm8F33qN7hXJUhLumFgjLLVgktypznoNJPIiKPn1Ien9IgvCK/T9omcmkKMwyfP9fmM8qvzumvJoN7jOKEJsP03Bb8RB+qwGDT44nhXYghhLyvR+vLVXufxhgJ6VC/Yitx011aoA+XO+iPNJD4eOb+lt9TDWVVPe4uzHXhcC14R/vaK9AM2s8QkZydTYFA2tbAxb4HyHs1ZTI/bBTQ9tjVqmNJfGVrfitAQm/cq7KQa9+DT/vjgR1oeLDXmlfzILgJMMGlT31wVzcqZi9WNBElxEeNGct9pzyRneJY6Z2I9PBcoTWc8PilwVN8h8qS4MRkVhmScKWobUFm/58DUdGgz9TH27+FdfH4uBj8ISCJOy3GPSkM/pjwXmoSORZ2M3NMp+Sw4EgudEDzyJvPj62j5s56M6PdLuBsp9assgbqOPinDCEMkMk0mAw4Twv57vhfzDy6ueGhQz6GLtiaMrOqQ=
