{
 "title": "Alerts",
 "tags": [ "alertmanager" ],
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Region", "query": "REGION" },
   {
    "name": "AlbInternal",
    "query": "dimension_values($Region, AWS/ApplicationELB, TargetResponseTime, LoadBalancer)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health check failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "repeat": "alert",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"ALBHealthCheckFailed\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Kontti ei vastaa",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"ContainerUnavailable\"",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Boot loop",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"ContainerUnavailableRepeatedly\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "KI-indeksointi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"KiIndeksointiFailed\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "EC2-palvelin alhaalla",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"EC2NodeExporterUnavailable\"",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Sairas host ELBin takana",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"UnhealthyHosts\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Sairas ALB-targetti",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"UnhealthyTargetsInTargetGroup\"",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Internal ALB performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$AlbInternal" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$Region",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "LoadBalancer": "$AlbInternal" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "$Region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Kanta täynnä",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"RDSDiskFull\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Kanta täyttyy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"RDSDiskLow\"",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RDS IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"RDSBurstBalanceBeingUsed\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RDS CPU util",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"RDSCPUHigh\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RDS CPU-balanssi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"RDSCPUBalanceBeingUsed\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Backup käynnistetty",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=\"NoBackupInvocationToday\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Sairas Mongo-instanssi",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=\"UnhealthyMongoHosts\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Levy täynnä",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"EC2NodeFullDisk\"",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Levy vähissä",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"EC2NodeLowDisk\"",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Levy täyttyy 1h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"DiskWillFillVerySoon\"",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Levy täyttyy 72h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=~\"DiskWillFillSoon\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Backup onnistunut",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "alertname=\"NoSuccessfulBackupToday\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Pingdom failing / total", "type": "ryantxu-ajax-panel", "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 } },
  {
   "title": "Hälytykset",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 9 },
   "targets": [
    { "labelSelector": "description", "legendFormat": "{{description}}", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "ALB error rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$AlbInternal" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$Region",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "LoadBalancer": "$AlbInternal" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$Region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Sähköpostibounceja",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(aws_ses_reputation_bounce_rate_average[30m])*100",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Roskapostivalituksia",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "aws_ses_reputation_complaint_rate_average*100",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  }
 ]
}